import Layout from '@/components/Layout';
import Section from '@/components/Section';
import Container from '@/components/Container';
import Button from '@/components/Button';
import styles from '@/styles/Home.module.scss';
import Image from 'next/image';
import Hero1 from '../../public/images/hero-one.svg'
import Hero2 from '../../public/images/hero-two.svg'
import Graph from '../../public/images/graph.png'

export default function Home() {


  return (
    <Layout>
      <Section>
        <Container className={styles.homeContainer}>
        <Container className={styles.homeContain}>
        <div className={styles.contain}>
        <h1>Track and Reduce Your Website's Carbon Emissions</h1>
        <Button className="btn">Calculate Now</Button>
        </div>
        <Image src={Hero1} width={450} height={450} alt='hero'/>
        </Container>
        </Container>
      </Section>
      <Section>
        <Container className={styles.infoContainer}>
        <Container className={styles.infoContain}>
        <div className={styles.contain}>
        <p className={styles.p1}>Make a positive impact on the environment by understanding and 
          minimizing the carbon footprint of your website. </p>
          <p className={styles.p2}>CarbonConscious helps you measure and visualize  the emissions generated by your 
            website, empowering you to take meaningful steps towards sustainability.</p>
        <Button className="btn">Learn How</Button>
        </div>
        <Image src={Hero2} width={450} height={450} alt='hero'/>
        </Container>
        </Container>
      </Section>

      <Section>
        <Container className={styles.graphContainer}>
        <Container className={styles.graphContain}>
        <h1>Why Measure Your Website's Carbon Emissions?</h1>
        <p>Understanding and measuring your website's carbon emissions is crucial in the fight 
          against climate change. By taking responsibility for the environmental impact of 
          your online presence, you contribute to the collective effort of
           creating a sustainable future.</p>
           <Image src={Graph} alt='graph'/>
           <a href='https://almanac.httparchive.org/en/2022/sustainability#carbon-emissions' target='_blank'>https://almanac.httparchive.org/en/2022/sustainability#carbon-emissions</a>
        </Container>
        </Container>
      </Section>
     

      <Section>
        <Container className={styles.graphContainer}>
        <Container className={styles.graphContain}>
        <h1>Why Measure Your Website's Carbon Emissions?</h1>
        <p>Understanding and measuring your website's carbon emissions is crucial in the fight 
          against climate change. By taking responsibility for the environmental impact of 
          your online presence, you contribute to the collective effort of
           creating a sustainable future.</p>
           <Image src={Graph} alt='graph'/>
           <a href='https://almanac.httparchive.org/en/2022/sustainability#carbon-emissions' target='_blank'>https://almanac.httparchive.org/en/2022/sustainability#carbon-emissions</a>
        </Container>
        </Container>
      </Section>
    </Layout>
  )
}